language: php
addons:
  ssh_known_hosts:
  - "$STAGING_SERVER"
  - "$PRODUCTION_SERVER"
script:
  -
before_deploy:
  - openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-staging.sh
    on:
      branch: staging
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-production.sh
    on:
      branch: master
